name : checkout
on : workflow_dispatch
jobs:
  no-checkout-job :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout repository
        run : cat README.md

  checkout-job :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout repository
        uses : actions/checkout@v4
      - name : Verify checkout
        run : cat README.md

  slack:
    runs on: ubuntu-latest
    environment: dev
    steps:
    - name: post a message in a channel
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook: ${{ secrets.slack_webhook_url }}
        webhook-type: incoming-webhook
        payload: |
          text: "message from checkout.yaml workflow"
